export const dataTable = [
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552351",
    "customerName": "James Witcwicky",
    "value": "R$ 50,00",
    "paid": "Sim",
    "descPlane": "Descrição do Plano",
    "namePlane": "Standard",
    "availability": "Apenas período da noite",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552352",
    "customerName": "Sarah Connors",
    "namePlane": "Basic",
    "descPlane": "Descrição do Plano",
    "value": "R$ 100,00",
    "paid": "Não",
    "availability": "Qualquer horário",
    "type": "Documento",
    "communication": "WhatsApp",
    "status": "Clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Pago"
  },
  {
    "orderNumber": "#5552353",
    "customerName": "John Doe",
    "value": "R$ 200,00",
    "namePlane": "Premium",
    "descPlane": "Descrição do Plano",
    "paid": "Sim",
    "availability": "Apenas período da manhã",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552354",
    "customerName": "Jane Smith",
    "value": "R$ 300,00",
    "descPlane": "Descrição do Plano",
    "paid": "Não",
    "availability": "Apenas período da tarde",
    "type": "Documento",
    "communication": "WhatsApp",
    "status": "Clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552355",
    "customerName": "Robert Langdon",
    "value": "R$ 400,00",
    "paid": "Sim",
    "availability": "Qualquer horário",
    "descPlane": "Descrição do Plano",
    "type": "Arquivo",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Avaliação"
  },
  {
    "orderNumber": "#5552356",
    "customerName": "Sophie Neveu",
    "value": "R$ 500,00",
    "descPlane": "Descrição do Plano",
    "paid": "Não",
    "availability": "Apenas período da noite",
    "type": "Documento",
    "communication": "WhatsApp",
    "status": "Clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Nova Assinatura"
  },
  {
    "orderNumber": "#5552356",
    "customerName": "Sophie Neveu",
    "value": "R$ 500,00",
    "paid": "Não",
    "availability": "Apenas período da noite",
    "type": "Documento",
    "descPlane": "Descrição do Plano",
    "communication": "WhatsApp",
    "status": "Não clicou no whatsapp",
    "data": "06 de Junho de 2023",
    "status_signature": "Pago"
  }
]
